ebook_metadata:
  title: ༄༅། །སྐུ་གསུམ་ཞིང་ཁམས་སྦྱོང་བའི་གསོལ་འདེབས་སྨོན་ལམ་གྱི་འགྲེལ་པ་གཏན་བདེའི་ས་བོན་བཞུགས་སོ།
    །
  authors:
  - མཛད་པ་པོ། ༧སྐྱབས་རྗེ་དིལ་མགོ་མཁྱེན་བཙེ་རིན་པོ་ཆེ།
  sku: SHE-DKR-12
  layers:
  - book_title
  - author
  - yigchung
web_metadata:
  title:
    en: A Seed for Stable Bliss:A Commentary on the Supplication Prayer of Purifying
      the Three Bodies
    bo: སྐུ་གསུམ་ཞིང་ཁམས་སྦྱོང་བའི་གསོལ་འདེབས་སྨོན་ལམ་གྱི་འགྲེལ་པ་གཏན་བདེའི་ས་བོན་བཞུགས་སོ།
  collection:
    en: Dilgo Khyentse Series–  Book 12
    bo: དིལ་མགོ་མཁྱེན་བཙེ་གསུང་འབུམ།–  དེབ། ༡༢
  author:
    en: Kyabje Dilgo Khyentse Rinpoche
    bo: ༧སྐྱབས་རྗེ་དིལ་མགོ་མཁྱེན་བཙེ་རིན་པོ་ཆེ།
  pusblisher:
    en: Shechen Publications
    bo: ཞེ་ཆེན་བསྟན་གཉིས་དར་རྒྱས་གླིང།
  sku: SHE-DKR-12
  category:
    en: Uncategorized
    bo: Uncategorized @tib
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: SHE-DKR-12.epub
  description:
    en: ''
    bo: ''
